require('./bootstrap')
require('../adminlte/plugins/bootstrap/js/bootstrap.bundle')
require('../adminlte/plugins/datatables/jquery.dataTables')
require('../adminlte/dist/js/adminlte')
require('../adminlte/dist/js/demo')